name: Run AIVA Test Batch

on:
  workflow_dispatch:
    inputs:
      LABELS:
        description: "Label of the tests that should be run"
        type: string
        default: "" 
      MAX_NUMBER_OF_AGENTS:
        description: "Maximum number of AIVA agents that can be used for running tests"
        type: number
        default: "" 
      TEST_NAME:
        description: "Optional name for the test batch"
        type: string
        default: "" 
      GLOBAL_OVERRIDES: 
        description: "Overrides variables in all tests"
        type: string
        default: "" 
      OVERRIDES_PER_TEST: 
        description: "Overrides variables in test specifid by test ID"
        type: string
        default: "" 
      GATEWAY_NAME: 
        description: "Uses a specified gateway during batch run"
        type: string
        default: ""
      POLL_PERIOD:
        description: "How often to repeat the AIVA call for batch status"
        type: number
        default: 10
      REPORT_FILEPATH:
        description: "Path to report from batch run."
        type: string
        default: "./batch-ctrf.json"

jobs:
  aiva_batch_job:
    name: Run AIVA batch (example)
    runs-on: ubuntu-latest

    steps:
      - name: Start AIVA batch
        id: aiva
        uses: aiva-actions/run@initial-customization
        with:
          apiKey: ${{ secrets.APIKEY }}
          labels: ${{ inputs.LABELS}}
          maxNumberOfAgents: ${{ inputs.MAX_NUMBER_OF_AGENTS }}
          testName: ${{ inputs.TEST_NAME }}
          globalVariableOverrides: ${{ inputs.GLOBAL_OVERRIDES }}
          variableOverridesPerTest: ${{ inputs.OVERRIDES_PER_TEST }}
          gatewayName: ${{ inputs.GATEWAY_NAME }}
          pollPeriodSeconds: ${{ inputs.POLL_PERIOD }}
          reportFilePath: ${{ inputs.REPORT_FILEPATH }}

      - name: Download Summary template
        id: template-download
        run: wget https://github.com/aiva-actions/run/blob/initial-customization/summary-template.hbs -O ./summary-template.hbs

      - name: ls
        id: ls current dir
        run: ls -lha
        
      - name: Generate CTRF summary
        id: summary
        uses: ctrf-io/github-test-reporter@v1.0.28
        with:
          report-path: ${{ inputs.REPORT_FILEPATH }}
          template-path: 'summary-template.hbs'
          custom-report: true
        if: always()

